export interface Country {
  name: string;
  code: string;
  dialCode: string;
  format: string;
}

export const CountryData = {
  getAll: (): Country[] => [
    { name: "Afghanistan", code: "AF", dialCode: "+93", format: "## ### ####" },
    { name: "Albania", code: "AL", dialCode: "+355", format: "(###) ### ###" },
    { name: "Algeria", code: "DZ", dialCode: "+213", format: "### ## ## ##" },
    { name: "Andorra", code: "AD", dialCode: "+376", format: "### ###" },
    { name: "Angola", code: "AO", dialCode: "+244", format: "### ### ###" },
    {
      name: "Antigua and Barbuda",
      code: "AG",
      dialCode: "+1268",
      format: "### ####",
    },
    { name: "Argentina", code: "AR", dialCode: "+54", format: "## ####-####" },
    { name: "Armenia", code: "AM", dialCode: "+374", format: "## ######" },
    { name: "Australia", code: "AU", dialCode: "+61", format: "### ### ###" },
    { name: "Austria", code: "AT", dialCode: "+43", format: "### ######" },
    {
      name: "Azerbaijan",
      code: "AZ",
      dialCode: "+994",
      format: "## ### ## ##",
    },
    { name: "Bahamas", code: "BS", dialCode: "+1242", format: "### ####" },
    { name: "Bahrain", code: "BH", dialCode: "+973", format: "#### ####" },
    { name: "Bangladesh", code: "BD", dialCode: "+880", format: "#### ######" },
    { name: "Barbados", code: "BB", dialCode: "+1246", format: "### ####" },
    { name: "Belarus", code: "BY", dialCode: "+375", format: "## ### ## ##" },
    { name: "Belgium", code: "BE", dialCode: "+32", format: "### ## ## ##" },
    { name: "Belize", code: "BZ", dialCode: "+501", format: "### ####" },
    { name: "Benin", code: "BJ", dialCode: "+229", format: "## ## ####" },
    { name: "Bhutan", code: "BT", dialCode: "+975", format: "## ### ###" },
    { name: "Bolivia", code: "BO", dialCode: "+591", format: "# ### ####" },
    {
      name: "Bosnia and Herzegovina",
      code: "BA",
      dialCode: "+387",
      format: "## ### ###",
    },
    { name: "Botswana", code: "BW", dialCode: "+267", format: "## ### ###" },
    { name: "Brazil", code: "BR", dialCode: "+55", format: "(##) #####-####" },
    { name: "Brunei", code: "BN", dialCode: "+673", format: "### ####" },
    { name: "Bulgaria", code: "BG", dialCode: "+359", format: "### ### ###" },
    {
      name: "Burkina Faso",
      code: "BF",
      dialCode: "+226",
      format: "## ## ####",
    },
    { name: "Burundi", code: "BI", dialCode: "+257", format: "## ## ####" },
    { name: "Cambodia", code: "KH", dialCode: "+855", format: "## ### ###" },
    { name: "Cameroon", code: "CM", dialCode: "+237", format: "#### ## ##" },
    { name: "Canada", code: "CA", dialCode: "+1", format: "(###) ###-####" },
    { name: "Cape Verde", code: "CV", dialCode: "+238", format: "### ####" },
    {
      name: "Central African Republic",
      code: "CF",
      dialCode: "+236",
      format: "## ## ####",
    },
    { name: "Chad", code: "TD", dialCode: "+235", format: "## ## ## ##" },
    { name: "Chile", code: "CL", dialCode: "+56", format: "# #### ####" },
    { name: "China", code: "CN", dialCode: "+86", format: "### #### ####" },
    { name: "Colombia", code: "CO", dialCode: "+57", format: "### ### ####" },
    { name: "Comoros", code: "KM", dialCode: "+269", format: "### ####" },
    { name: "Congo", code: "CG", dialCode: "+242", format: "## ### ####" },
    { name: "Costa Rica", code: "CR", dialCode: "+506", format: "#### ####" },
    { name: "Croatia", code: "HR", dialCode: "+385", format: "## ### ####" },
    { name: "Cuba", code: "CU", dialCode: "+53", format: "# ### ####" },
    { name: "Cyprus", code: "CY", dialCode: "+357", format: "## ######" },
    {
      name: "Czech Republic",
      code: "CZ",
      dialCode: "+420",
      format: "### ### ###",
    },
    { name: "Denmark", code: "DK", dialCode: "+45", format: "## ## ## ##" },
    { name: "Djibouti", code: "DJ", dialCode: "+253", format: "## ## ## ##" },
    { name: "Dominica", code: "DM", dialCode: "+1767", format: "### ####" },
    {
      name: "Dominican Republic",
      code: "DO",
      dialCode: "+1849",
      format: "### ###-####",
    },
    { name: "East Timor", code: "TL", dialCode: "+670", format: "#### ####" },
    { name: "Ecuador", code: "EC", dialCode: "+593", format: "## ### ####" },
    { name: "Egypt", code: "EG", dialCode: "+20", format: "### ### ####" },
    { name: "El Salvador", code: "SV", dialCode: "+503", format: "#### ####" },
    {
      name: "Equatorial Guinea",
      code: "GQ",
      dialCode: "+240",
      format: "## ### ####",
    },
    { name: "Eritrea", code: "ER", dialCode: "+291", format: "# ### ###" },
    { name: "Estonia", code: "EE", dialCode: "+372", format: "### ####" },
    { name: "Ethiopia", code: "ET", dialCode: "+251", format: "## ### ####" },
    { name: "Fiji", code: "FJ", dialCode: "+679", format: "## #####" },
    { name: "Finland", code: "FI", dialCode: "+358", format: "### ### ## ##" },
    { name: "France", code: "FR", dialCode: "+33", format: "# ## ## ## ##" },
    { name: "Gabon", code: "GA", dialCode: "+241", format: "# ## ## ##" },
    { name: "Gambia", code: "GM", dialCode: "+220", format: "### ####" },
    { name: "Georgia", code: "GE", dialCode: "+995", format: "### ### ###" },
    { name: "Germany", code: "DE", dialCode: "+49", format: "### ##########" },
    { name: "Ghana", code: "GH", dialCode: "+233", format: "### ### ###" },
    { name: "Greece", code: "GR", dialCode: "+30", format: "### ### ####" },
    { name: "Grenada", code: "GD", dialCode: "+1473", format: "### ####" },
    { name: "Guatemala", code: "GT", dialCode: "+502", format: "#### ####" },
    { name: "Guinea", code: "GN", dialCode: "+224", format: "### ### ###" },
    { name: "Guinea-Bissau", code: "GW", dialCode: "+245", format: "### ####" },
    { name: "Guyana", code: "GY", dialCode: "+592", format: "### ####" },
    { name: "Haiti", code: "HT", dialCode: "+509", format: "## ## ####" },
    { name: "Honduras", code: "HN", dialCode: "+504", format: "#### ####" },
    { name: "Hungary", code: "HU", dialCode: "+36", format: "## ### ####" },
    { name: "Iceland", code: "IS", dialCode: "+354", format: "### ####" },
    { name: "India", code: "IN", dialCode: "+91", format: "##### #####" },
    { name: "Indonesia", code: "ID", dialCode: "+62", format: "### ### ###" },
    { name: "Iran", code: "IR", dialCode: "+98", format: "### ### ####" },
    { name: "Iraq", code: "IQ", dialCode: "+964", format: "### ### ####" },
    { name: "Ireland", code: "IE", dialCode: "+353", format: "## ### ####" },
    { name: "Israel", code: "IL", dialCode: "+972", format: "### ### ####" },
    { name: "Italy", code: "IT", dialCode: "+39", format: "### ### ####" },
    { name: "Jamaica", code: "JM", dialCode: "+1876", format: "### ####" },
    { name: "Japan", code: "JP", dialCode: "+81", format: "## #### ####" },
    { name: "Jordan", code: "JO", dialCode: "+962", format: "# #### ####" },
    { name: "Kazakhstan", code: "KZ", dialCode: "+7", format: "### ### ## ##" },
    { name: "Kenya", code: "KE", dialCode: "+254", format: "### ######" },
    { name: "Kiribati", code: "KI", dialCode: "+686", format: "## ###" },
    { name: "Kuwait", code: "KW", dialCode: "+965", format: "#### ####" },
    { name: "Kyrgyzstan", code: "KG", dialCode: "+996", format: "### ### ###" },
    { name: "Laos", code: "LA", dialCode: "+856", format: "## ### ###" },
    { name: "Latvia", code: "LV", dialCode: "+371", format: "## ### ###" },
    { name: "Lebanon", code: "LB", dialCode: "+961", format: "## ### ###" },
    { name: "Lesotho", code: "LS", dialCode: "+266", format: "# ### ####" },
    { name: "Liberia", code: "LR", dialCode: "+231", format: "## ### ###" },
    { name: "Libya", code: "LY", dialCode: "+218", format: "## ### ####" },
    {
      name: "Liechtenstein",
      code: "LI",
      dialCode: "+423",
      format: "### ### ###",
    },
    { name: "Lithuania", code: "LT", dialCode: "+370", format: "### #####" },
    { name: "Luxembourg", code: "LU", dialCode: "+352", format: "### ### ###" },
    { name: "Macedonia", code: "MK", dialCode: "+389", format: "## ### ###" },
    { name: "Madagascar", code: "MG", dialCode: "+261", format: "## ## #####" },
    { name: "Malawi", code: "MW", dialCode: "+265", format: "# ### ###" },
    { name: "Malaysia", code: "MY", dialCode: "+60", format: "## ### ####" },
    { name: "Maldives", code: "MV", dialCode: "+960", format: "### ####" },
    { name: "Mali", code: "ML", dialCode: "+223", format: "## ## ####" },
    { name: "Malta", code: "MT", dialCode: "+356", format: "#### ####" },
    {
      name: "Marshall Islands",
      code: "MH",
      dialCode: "+692",
      format: "### ####",
    },
    { name: "Mauritania", code: "MR", dialCode: "+222", format: "## ## ####" },
    { name: "Mauritius", code: "MU", dialCode: "+230", format: "#### ####" },
    { name: "Mexico", code: "MX", dialCode: "+52", format: "### ### ####" },
    { name: "Micronesia", code: "FM", dialCode: "+691", format: "### ####" },
    { name: "Moldova", code: "MD", dialCode: "+373", format: "### ## ###" },
    { name: "Monaco", code: "MC", dialCode: "+377", format: "## ## ## ##" },
    { name: "Mongolia", code: "MN", dialCode: "+976", format: "## ## ####" },
    { name: "Montenegro", code: "ME", dialCode: "+382", format: "## ### ###" },
    { name: "Morocco", code: "MA", dialCode: "+212", format: "## #### ###" },
    { name: "Mozambique", code: "MZ", dialCode: "+258", format: "## ### ###" },
    { name: "Myanmar", code: "MM", dialCode: "+95", format: "# ### ###" },
    { name: "Namibia", code: "NA", dialCode: "+264", format: "## ### ####" },
    { name: "Nauru", code: "NR", dialCode: "+674", format: "### ####" },
    { name: "Nepal", code: "NP", dialCode: "+977", format: "## ### ###" },
    {
      name: "Netherlands",
      code: "NL",
      dialCode: "+31",
      format: "# ## ## ## ##",
    },
    { name: "New Zealand", code: "NZ", dialCode: "+64", format: "## ### ####" },
    { name: "Nicaragua", code: "NI", dialCode: "+505", format: "#### ####" },
    { name: "Niger", code: "NE", dialCode: "+227", format: "## ## ####" },
    { name: "Nigeria", code: "NG", dialCode: "+234", format: "### ### ####" },
    { name: "North Korea", code: "KP", dialCode: "+850", format: "## ### ###" },
    { name: "Norway", code: "NO", dialCode: "+47", format: "### ## ###" },
    { name: "Oman", code: "OM", dialCode: "+968", format: "#### ####" },
    { name: "Pakistan", code: "PK", dialCode: "+92", format: "(###) ### ####" },
    { name: "Palau", code: "PW", dialCode: "+680", format: "### ####" },
    { name: "Palestine", code: "PS", dialCode: "+970", format: "## ### ####" },
    { name: "Panama", code: "PA", dialCode: "+507", format: "#### ####" },
    {
      name: "Papua New Guinea",
      code: "PG",
      dialCode: "+675",
      format: "### ####",
    },
    { name: "Paraguay", code: "PY", dialCode: "+595", format: "(###) ### ###" },
    { name: "Peru", code: "PE", dialCode: "+51", format: "### ### ###" },
    {
      name: "Philippines",
      code: "PH",
      dialCode: "+63",
      format: "(###) ### ####",
    },
    { name: "Poland", code: "PL", dialCode: "+48", format: "### ### ###" },
    { name: "Portugal", code: "PT", dialCode: "+351", format: "### ### ###" },
    { name: "Qatar", code: "QA", dialCode: "+974", format: "#### ####" },
    { name: "Romania", code: "RO", dialCode: "+40", format: "### ### ###" },
    { name: "Russia", code: "RU", dialCode: "+7", format: "(###) ###-##-##" },
    { name: "Rwanda", code: "RW", dialCode: "+250", format: "(###) ### ###" },
    {
      name: "Saint Kitts and Nevis",
      code: "KN",
      dialCode: "+1869",
      format: "### ####",
    },
    { name: "Saint Lucia", code: "LC", dialCode: "+1758", format: "### ####" },
    {
      name: "Saint Vincent and the Grenadines",
      code: "VC",
      dialCode: "+1784",
      format: "### ####",
    },
    { name: "Samoa", code: "WS", dialCode: "+685", format: "## ####" },
    { name: "San Marino", code: "SM", dialCode: "+378", format: "#### ######" },
    {
      name: "Sao Tome and Principe",
      code: "ST",
      dialCode: "+239",
      format: "## #####",
    },
    {
      name: "Saudi Arabia",
      code: "SA",
      dialCode: "+966",
      format: "## ### ####",
    },
    { name: "Senegal", code: "SN", dialCode: "+221", format: "## ### ####" },
    { name: "Serbia", code: "RS", dialCode: "+381", format: "## ### ####" },
    { name: "Seychelles", code: "SC", dialCode: "+248", format: "# ### ###" },
    { name: "Sierra Leone", code: "SL", dialCode: "+232", format: "## ######" },
    { name: "Singapore", code: "SG", dialCode: "+65", format: "#### ####" },
    { name: "Slovakia", code: "SK", dialCode: "+421", format: "### ### ###" },
    { name: "Slovenia", code: "SI", dialCode: "+386", format: "## ### ###" },
    {
      name: "Solomon Islands",
      code: "SB",
      dialCode: "+677",
      format: "### ####",
    },
    { name: "Somalia", code: "SO", dialCode: "+252", format: "## ### ###" },
    {
      name: "South Africa",
      code: "ZA",
      dialCode: "+27",
      format: "## ### ####",
    },
    {
      name: "South Sudan",
      code: "SS",
      dialCode: "+211",
      format: "## ### ####",
    },
    { name: "Spain", code: "ES", dialCode: "+34", format: "### ### ###" },
    { name: "Sri Lanka", code: "LK", dialCode: "+94", format: "## ### ####" },
    { name: "Sudan", code: "SD", dialCode: "+249", format: "## ### ####" },
    { name: "Suriname", code: "SR", dialCode: "+597", format: "### ####" },
    { name: "Sweden", code: "SE", dialCode: "+46", format: "## ### ####" },
    { name: "Switzerland", code: "CH", dialCode: "+41", format: "## ### ####" },
    { name: "Syria", code: "SY", dialCode: "+963", format: "## ### ####" },
    { name: "Taiwan", code: "TW", dialCode: "+886", format: "### ### ###" },
    { name: "Tajikistan", code: "TJ", dialCode: "+992", format: "## ### ####" },
    { name: "Tanzania", code: "TZ", dialCode: "+255", format: "## ### ####" },
    { name: "Thailand", code: "TH", dialCode: "+66", format: "## ### ####" },
    { name: "Timor-Leste", code: "TL", dialCode: "+670", format: "### ####" },
    { name: "Togo", code: "TG", dialCode: "+228", format: "## ### ###" },
    { name: "Tonga", code: "TO", dialCode: "+676", format: "### ####" },
    {
      name: "Trinidad and Tobago",
      code: "TT",
      dialCode: "+1868",
      format: "### ####",
    },
    { name: "Tunisia", code: "TN", dialCode: "+216", format: "## ### ###" },
    { name: "Turkey", code: "TR", dialCode: "+90", format: "### ### ####" },
    { name: "Turkmenistan", code: "TM", dialCode: "+993", format: "## ######" },
    { name: "Tuvalu", code: "TV", dialCode: "+688", format: "## ###" },
    { name: "Uganda", code: "UG", dialCode: "+256", format: "### ### ###" },
    { name: "Ukraine", code: "UA", dialCode: "+380", format: "## ### ####" },
    {
      name: "United Arab Emirates",
      code: "AE",
      dialCode: "+971",
      format: "## ### ####",
    },
    {
      name: "United Kingdom",
      code: "GB",
      dialCode: "+44",
      format: "#### ######",
    },
    {
      name: "United States",
      code: "US",
      dialCode: "+1",
      format: "(###) ###-####",
    },
    { name: "Uruguay", code: "UY", dialCode: "+598", format: "# ### ####" },
    { name: "Uzbekistan", code: "UZ", dialCode: "+998", format: "## ### ####" },
    { name: "Vanuatu", code: "VU", dialCode: "+678", format: "### ####" },
    {
      name: "Vatican City",
      code: "VA",
      dialCode: "+39",
      format: "06 698#####",
    },
    { name: "Venezuela", code: "VE", dialCode: "+58", format: "### ### ####" },
    { name: "Vietnam", code: "VN", dialCode: "+84", format: "## #### ####" },
    { name: "Yemen", code: "YE", dialCode: "+967", format: "## ### ###" },
    { name: "Zambia", code: "ZM", dialCode: "+260", format: "## ### ####" },
    { name: "Zimbabwe", code: "ZW", dialCode: "+263", format: "## ### ####" },
  ],
};
